server:
  port: 18087

spring:
  application:
    name: dubbo-provider

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: zookeeper://192.168.2.18:2181
    timeout: 2000
  protocol:
    name: dubbo
    port: 20890
  # 扫描 @DubboService 注解
  scan:
    base-packages: com.dubbo.provider.service
