server:
  port: 18089

spring:
  application:
    name: dubbo-provider1

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: zookeeper://192.168.2.18:2181
    timeout: 2000
  protocol:
    name:  { "dubbo", "hessian" }
    port: 20881
  # 扫描 @DubboService 注解
  scan:
    base-packages: com.dubbo.provider.service
